# -*- mode: dockerfile -*-

FROM nvidia/cuda:12.6.2-cudnn-devel-ubuntu22.04

ARG PYTHON_VERSION=3.8
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -yq \
        bison \
        build-essential \
        cmake \
        curl \
        flex \
        git \
        libbz2-dev \
        ninja-build \
        wget \
        gedit

WORKDIR /opt/conda_setup

RUN curl -o miniconda.sh https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh && \
     chmod +x miniconda.sh && \
     ./miniconda.sh -b -p /opt/conda && \
     /opt/conda/bin/conda install -y python=$PYTHON_VERSION && \
     /opt/conda/bin/conda clean -ya
ENV PATH /opt/conda/bin:$PATH

RUN python -m pip install --upgrade pip ipython ipdb

COPY . /opt/minihack/

WORKDIR /opt/minihack

RUN pip3 install matplotlib==3.5.0
RUN pip install '.[all]'

WORKDIR /workspace

CMD ["/bin/bash"]


# Docker commands:
#   docker rm minihack -v
#   docker build -t minihack -f docker/Dockerfile .
#   docker run --rm --name minihack minihack
# or
#   docker run -it --entrypoint /bin/bash minihack
